"""create calculation cases table

Revision ID: cbfc55903131
Revises: a2849c0e6b39
Create Date: 2026-08-09 04:49:11.590767

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cbfc55903131"
down_revision: str | Sequence[str] | None = "a2849c0e6b39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculation_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("calculation_code", sa.String(length=50), nullable=False),
        sa.Column("calculation_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engineering_notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calculation_cases_calculation_code"),
        "calculation_cases",
        ["calculation_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_calculation_cases_calculation_type"),
        "calculation_cases",
        ["calculation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calculation_cases_project_id"), "calculation_cases", ["project_id"], unique=False
    )
    op.create_index(
        "ix_calculation_cases_project_status",
        "calculation_cases",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_calculation_cases_project_type",
        "calculation_cases",
        ["project_id", "calculation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calculation_cases_status"), "calculation_cases", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calculation_cases_status"), table_name="calculation_cases")
    op.drop_index("ix_calculation_cases_project_type", table_name="calculation_cases")
    op.drop_index("ix_calculation_cases_project_status", table_name="calculation_cases")
    op.drop_index(op.f("ix_calculation_cases_project_id"), table_name="calculation_cases")
    op.drop_index(op.f("ix_calculation_cases_calculation_type"), table_name="calculation_cases")
    op.drop_index(op.f("ix_calculation_cases_calculation_code"), table_name="calculation_cases")
    op.drop_table("calculation_cases")
    # ### end Alembic commands ###
