"""C-9a add compressed air leakage lifecycle tables

Revision ID: d13bc3d26430
Revises: dec0662d209f
Create Date: 2026-09-08 13:39:25.884578

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d13bc3d26430"
down_revision: str | Sequence[str] | None = "dec0662d209f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compressed_air_leaks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("leak_code", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("source_snapshot", sa.JSON(), nullable=False),
        sa.Column("closure_evidence", sa.JSON(), nullable=True),
        sa.Column("closure_notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("tagged_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "leak_code", name="uq_compressed_air_leaks_project_code"),
    )
    op.create_index(
        op.f("ix_compressed_air_leaks_assigned_to"),
        "compressed_air_leaks",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leaks_leak_code"),
        "compressed_air_leaks",
        ["leak_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leaks_lifecycle_status"),
        "compressed_air_leaks",
        ["lifecycle_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leaks_project_id"),
        "compressed_air_leaks",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "compressed_air_leak_kpi_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("leak_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_code", sa.String(length=100), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("metrics_payload", sa.JSON(), nullable=False),
        sa.Column("captured_by", sa.String(length=255), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["leak_id"], ["compressed_air_leaks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "leak_id", "snapshot_code", name="uq_compressed_air_leak_kpi_snapshots_leak_code"
        ),
    )
    op.create_index(
        op.f("ix_compressed_air_leak_kpi_snapshots_captured_at"),
        "compressed_air_leak_kpi_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leak_kpi_snapshots_leak_id"),
        "compressed_air_leak_kpi_snapshots",
        ["leak_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leak_kpi_snapshots_lifecycle_status"),
        "compressed_air_leak_kpi_snapshots",
        ["lifecycle_status"],
        unique=False,
    )
    op.create_table(
        "compressed_air_leak_status_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("leak_id", sa.Integer(), nullable=False),
        sa.Column("previous_status", sa.String(length=30), nullable=True),
        sa.Column("new_status", sa.String(length=30), nullable=False),
        sa.Column("changed_by", sa.String(length=255), nullable=True),
        sa.Column("change_notes", sa.Text(), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["leak_id"], ["compressed_air_leaks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compressed_air_leak_status_history_changed_at"),
        "compressed_air_leak_status_history",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leak_status_history_leak_id"),
        "compressed_air_leak_status_history",
        ["leak_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compressed_air_leak_status_history_new_status"),
        "compressed_air_leak_status_history",
        ["new_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_compressed_air_leak_status_history_new_status"),
        table_name="compressed_air_leak_status_history",
    )
    op.drop_index(
        op.f("ix_compressed_air_leak_status_history_leak_id"),
        table_name="compressed_air_leak_status_history",
    )
    op.drop_index(
        op.f("ix_compressed_air_leak_status_history_changed_at"),
        table_name="compressed_air_leak_status_history",
    )
    op.drop_table("compressed_air_leak_status_history")
    op.drop_index(
        op.f("ix_compressed_air_leak_kpi_snapshots_lifecycle_status"),
        table_name="compressed_air_leak_kpi_snapshots",
    )
    op.drop_index(
        op.f("ix_compressed_air_leak_kpi_snapshots_leak_id"),
        table_name="compressed_air_leak_kpi_snapshots",
    )
    op.drop_index(
        op.f("ix_compressed_air_leak_kpi_snapshots_captured_at"),
        table_name="compressed_air_leak_kpi_snapshots",
    )
    op.drop_table("compressed_air_leak_kpi_snapshots")
    op.drop_index(op.f("ix_compressed_air_leaks_project_id"), table_name="compressed_air_leaks")
    op.drop_index(
        op.f("ix_compressed_air_leaks_lifecycle_status"), table_name="compressed_air_leaks"
    )
    op.drop_index(op.f("ix_compressed_air_leaks_leak_code"), table_name="compressed_air_leaks")
    op.drop_index(op.f("ix_compressed_air_leaks_assigned_to"), table_name="compressed_air_leaks")
    op.drop_table("compressed_air_leaks")
    # ### end Alembic commands ###
